sudo: required

services:
  - docker

before_install:
  - docker build -t rafaelnasc1mento/docker-react -f Dockerfile.dev

script:
  - docker run rafaelnasc1mento/docker-react npm run test -- --coverage
