version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      # /app/node_modules don't map this folder inside the container to anything, keep it as it is
      - /app/node_modules
      # maps the app folder inside the container to the current dir (pwd)
      - .:/app
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]
